# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e8f9398aac2c51588ec1ad6d727e3c8dd60fd2eff9afafed0d2aac7e23ef5b908ac56bc56bf28eb52c975c32cb7687094fd336501d976d48b8cf7c9f6fa48bd

test:
  secret_key_base: 498af16ad3b8694b4d52646c1f5c5b0f1ce1fd1b88fea0f3ff9f873bc417e9b19c106012a5195bbacfdb3c0e43b5f0a70ab7473b80d59f44313f1b305a273364

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
